development:
  adapter: mysql2
  database: rpg-master-development
  host: <%= ENV['MYSQL_HOST'] %>
  pool: 5
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>

test:
  adapter: mysql2
  database: rpg-master-test
  host: <%= ENV['MYSQL_HOST'] %>
  pool: 5
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
