development:
  adapter: postgresql
  database: rpg-master-development
  host: db
  port: <%= ENV['DB_PORT'] %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  adapter: postgresql
  database: rpg-master-test
  host: db
  port: <%= ENV['DB_PORT'] %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
