name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install MySQL
      run: apt-get install libmysqlclient-dev  
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Test
      run: bundle exec rspec
